Repository AY2324S2-CS2103T-T13-4/tp, pull requests merged in 2024-03, with the labels that each got.

#31 Update Documentation for AboutUs, DG and UG
  .gitignore
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/kokerinks.png
Labels: type.Documentation

#32 Update DG, UG and AboutUs (Khushi)
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/khushibhagwat.png
Labels: type.Documentation, priority.High

#33 Update AboutUs, README, UG (Kinjal)
  README.md
  docs/AboutUs.md
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/kinjalagarwal1810.png
Labels: priority.High

#36 Update filename to github username (Khushi)
  docs/AboutUs.md
  docs/images/kab-dot.png
Labels: type.Documentation, type.Individual_Task

#40 Add seedData functionality
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/SeedDataCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/commands/SeedDataCommandTest.java
Labels: type.Story

#41 Update UG for SeedData, Clear commands
  docs/UserGuide.md
Labels: type.Documentation

#39 Update Clear command to use --force tag
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ClearCommandParser.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/parser/ClearCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Labels: type.Story

#44 Create Add Membership Command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddMemshipCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddMemshipCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Membership.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddMemshipCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddMemshipCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story, priority.High

#42 Create AddPointsCommand
  docs/AboutUs.md
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddMemshipCommand.java
  src/main/java/seedu/address/logic/commands/AddPointsCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddPointsCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Points.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddMemshipCommandTest.java
  src/test/java/seedu/address/logic/commands/AddPointsCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddPointsCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/PointsTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story, priority.High

#45 Orders implementation
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddMemshipCommand.java
  src/main/java/seedu/address/logic/commands/AddOrderCommand.java
  src/main/java/seedu/address/logic/commands/AddPointsCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddOrderCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/orders/Order.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedOrder.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddOrderCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddOrderCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#53 Fixed bug for AddMemshipCommand
  src/main/java/seedu/address/logic/commands/AddMemshipCommand.java
Labels: priority.High

#50 Improve styling for application
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
Labels: priority.Low, type.Enhancement

#51 Add orders implementation in DG
  docs/DeveloperGuide.md
  docs/diagrams/AddOrderSequenceDiagram.puml
  docs/images/AddOrderSequenceDiagram.png
Labels: type.Documentation, priority.High

#58 Add new fields to BetterModelClassDiagram and ModelClassDiagram
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
Labels: type.Documentation, priority.High

#59 Add points implementation in DG
  docs/DeveloperGuide.md
  docs/diagrams/AddPointsSequenceDiagram.puml
  docs/images/AddPointsSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/AddPointsCommand.java
Labels: type.Documentation, priority.High

#67 Minor QOL changes
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddPointsCommand.java
  src/main/java/seedu/address/logic/parser/AddPointsCommandParser.java
  src/test/java/seedu/address/logic/parser/AddPointsCommandParserTest.java
Labels: priority.Medium, type.Bug

#73 Change seedData COMMAND_WORD to seeddata
  src/main/java/seedu/address/logic/commands/SeedDataCommand.java
Labels: type.Bug, severity.Low

#66 Add tracking of membership points to SweetRewards
  codecov.yml
  src/main/java/seedu/address/logic/commands/AddMemPointsCommand.java
  src/main/java/seedu/address/logic/commands/AddPointsCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddMemPointsCommandParser.java
  src/main/java/seedu/address/logic/parser/AddMemshipCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Membership.java
  src/main/java/seedu/address/model/person/MembershipPoints.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddMemPointsCommandTest.java
  src/test/java/seedu/address/logic/commands/AddMemshipCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddMemPointsCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddMemshipCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story, priority.High

#77 Update addmempts to take in n/NAME
  src/main/java/seedu/address/logic/commands/AddMemPointsCommand.java
  src/main/java/seedu/address/logic/parser/AddMemPointsCommandParser.java
  src/test/java/seedu/address/logic/parser/AddMemPointsCommandParserTest.java
Labels: type.Chore, severity.Low

#78 Branch v1.3 round off order time
  src/main/java/seedu/address/model/person/orders/Order.java
Labels: priority.Low, severity.Low
