Repository AY2324S2-CS2103T-T13-4/tp, pull requests merged in 2024-04, with the labels that each got.

#68 Item Order Integration
  codecov.yml
  src/main/java/seedu/address/logic/commands/AddOrderCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddOrderCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/item/Catalogue.java
  src/main/java/seedu/address/model/item/Item.java
  src/main/java/seedu/address/model/item/exceptions/DuplicateItemException.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Points.java
  src/main/java/seedu/address/model/person/orders/Order.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedItem.java
  src/main/java/seedu/address/storage/JsonAdaptedOrder.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddOrderCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddOrderCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/item/CatalogueTest.java
  src/test/java/seedu/address/model/item/ItemTest.java
  src/test/java/seedu/address/model/person/orders/OrderTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Enhancement

#86 Minor QOL improvements
  src/main/java/seedu/address/model/item/Catalogue.java
  src/main/java/seedu/address/model/person/MembershipPoints.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/MembershipPointsTest.java
Labels: type.Enhancement, type.Bug, severity.Low

#88 Add 'help --commands' to list all existing commands
  codecov.yml
  src/main/java/seedu/address/logic/commands/AddPointsCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/HelpCommandParser.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/parser/HelpCommandParserTest.java
Labels: priority.Medium, type.Enhancement

#96 Update UG to be consistant with v1.3
  docs/UserGuide.md
Labels: type.Documentation, priority.High

#97 Item integration- additem and delitem
  src/main/java/seedu/address/logic/commands/AddItemCommand.java
  src/main/java/seedu/address/logic/commands/AddPointsCommand.java
  src/main/java/seedu/address/logic/commands/DeleteItemCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/RedeemPointsCommand.java
  src/main/java/seedu/address/logic/parser/AddItemCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteItemCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/item/Catalogue.java
  src/main/java/seedu/address/model/item/Item.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddItemCommandTest.java
  src/test/java/seedu/address/logic/commands/AddPointsCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteItemCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddItemCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/item/CatalogueTest.java
Labels: priority.High

#107 Update landing page README.md
  README.md
Labels: type.Documentation, priority.Medium

#104 Improved error messsages for each command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddItemCommand.java
  src/main/java/seedu/address/logic/commands/AddMemPointsCommand.java
  src/main/java/seedu/address/logic/commands/AddOrderCommand.java
  src/main/java/seedu/address/logic/commands/AddPointsCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/RedeemPointsCommand.java
  src/main/java/seedu/address/logic/parser/AddMemPointsCommandParser.java
  src/main/java/seedu/address/logic/parser/HelpCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddPointsCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddMemPointsCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/HelpCommandParserTest.java
Labels: priority.Medium, type.Chore

#179 Fix additem for single character
  src/main/java/seedu/address/logic/commands/AddItemCommand.java
  src/main/java/seedu/address/model/item/Item.java
Labels: severity.High, bug.FeatureFlaw

#178 Fix seed data points
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: bug.FunctionalityBug

#183 UG fixes for v1.4
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/additem.png
  docs/images/addmem.png
  docs/images/addmempts.png
  docs/images/addorders.png
  docs/images/delitem.png
  docs/images/find.png
  docs/images/redeempts.png
  src/main/java/seedu/address/logic/commands/AddItemCommand.java
Labels: type.Documentation, priority.High

#184 Fix bug related to fractional quantities for the addorder command
  src/main/java/seedu/address/logic/parser/AddOrderCommandParser.java
Labels: priority.High, bug.FunctionalityBug

#185 V1.4 bugfixes
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddMembershipSequenceDiagram.puml
  docs/diagrams/AddOrderSequenceDiagram.puml
  docs/diagrams/AddPointsSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/style.puml
  docs/images/AddMembershipSequenceDiagram.png
  docs/images/AddOrderSequenceDiagram.png
  docs/images/AddPointsSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
  src/main/java/seedu/address/logic/commands/AddItemCommand.java
Labels: type.Documentation, priority.High
